public class DefaultIgnoreList {
    public static readonly string[] ignoreListIDs = {
        "slightGibberishTwistModule", "EverchangingModule", "pointerPointerModule", "inOrderModule", "nobodysCodeModule", "clearanceCodeModule","obscureRacesModule",
        "MemoryV2", "SouvenirModule", "HexiEvilFMN", "simonsStages",
        "forgetThis", "PurgatoryModule", "troll", "forgetThemAll",
        "tallorderedKeys", "forgetEnigma", "forgetUsNot", "qkForgetPerspective",
        "organizationModule", "veryAnnoyingButton", "forgetMeLater", "ubermodule",
        "qkUCN", "14", "forgetItNot", "simonForgets",
        "brainf", "ForgetTheColors", "RPSJudging", "TheTwinModule",
        "iconic", "omegaForget", "kugelblitz", "ANDmodule",
        "dontTouchAnything", "busyBeaver", "whiteout", "ForgetAnyColor",
        "KeypadDirectionality", "SecurityCouncil", "ShoddyChessModule", "FloorLights",
        "blackArrowsModule", "forgetMazeNot", "plus", "soulscream",
        "qkCubeSynchronization", "OutOfTime", "tetrahedron", "BoardWalk",
        "gemory", "duckKonundrum", "ConcentrationModule", "TwisterModule",
        "forgetOurVoices", "soulsong", "forgetMorseNot", "idExchange",
        "GSEight", "ultraCustomNight", "SimpleBoss", "SimpleBossNot",
        "KritGrandPrix", "ForgetMeMaybeModule", "simonSonundrum", "HyperForget",
        "qkBitwiseOblivion", "damoclesLumber", "top10nums", "squadsShadow",
        "queensWarModule", "forget_fractal", "memorysShadow", "PianoParadoxModule",
        "Omission", "BlackoutModule", "fizzBoss", "ActionsAndConsequences", "forgetle", "perspectiveStackingModule",

        "TurnTheKeyAdvanced", "theSwan", "DividedSquaresModule", "HogwartsModule", "cookieJars", "Krit4CardMonte", "encryptionBingo", "forgetInfinity", "mysterymodule", "multitask", "Amnesia", "FourtyTwo", "FiveZeroOne", "qkButtonMesser", "xelBMachine", "klaxon", "RemoteTurnTheKeys", "simonSemiboss", "scrabbleScramble", "speed", "peeky", "channelSurfing", "binary_memory", "damoclesLumber", "moduleManeuvers",
        "encryptedHangman", "TheHeart", "GSAccessCodes", "susadmin", "Mystery Widget",
        "xModule", "yModule", "bigShot", "CastorModule", "PolluxModule", "PineapplePenModule", "ApplePenModule",
        "TurnTheKey", "timeKeeper", "timingIsEverything", "bamboozlingTimeKeeper", "pwDestroyer", "omegaDestroyer", "kataZenerCards", "doomsdayButton", "redLightGreenLight", "repeatAgain",
        };
    public static readonly string[] ignoreListNames = {
        "Slight Gibberish Twist",
        "Everchanging",
        "Pointer Pointer",
        "In Order",
        "The Nobody's Code", "Clearance Code", "Obscure Races",
        "Forget Me Not",
        "Souvenir",
        "Forget Everything",
        "Simon's Stages",
        "Forget This",
        "Purgatory",
        "The Troll",
        "Forget Them All",
        "Tallordered Keys",
        "Forget Enigma",
        "Forget Us Not",
        "Forget Perspective",
        "Organization",
        "The Very Annoying Button", "Forget Me Later", "Übermodule", "Ultimate Custom Night", "14", "Forget It Not", "Simon Forgets", "Brainf---", "Forget The Colors", "RPS Judging", "The Twin", "Iconic", "OmegaForget", "Kugelblitz", "A>N<D", "Don't Touch Anything", "Busy Beaver", "Whiteout", "Forget Any Color", "Keypad Directionality", "Security Council", "Shoddy Chess", "Floor Lights", "Black Arrows", "Forget Maze Not", "+", "Soulscream", "Cube Synchronization", "Out of Time", "Tetrahedron", "The Board Walk", "Gemory", "Duck Konundrum", "Concentration", "Twister", "Forget Our Voices", "Soulsong", "Forget Morse Not", "ID Exchange", "8", "Ultra Custom Night", "Remember Simple", "Remembern't Simple", "The Grand Prix", "Forget Me Maybe", "Simon Sonundrum", "HyperForget", "Bitwise Oblivion", "Damocles Lumber", "Top 10 Numbers", "Squad's Shadow", "Memory's Shadow", "Turn The Keys", "The Swan", "Divided Squares", "Hogwarts", "Cookie Jars", "The Troll", "Four-Card Monte", "Encryption Bingo", "Forget Infinity", "Mystery Module", "Multitask", "Amnesia", "42", "501", "Button Messer", "B-Machine", "The Klaxon", "Custom Keys", "Simon", "Scrabble Scramble", "Forget Morse Not", "Ultra Custom Night", "Speedrun", "Peek-A-Boo", "Channel Surfing", "Binary Memory", "Damocles Lumber", "Module Maneuvers", "Squad's Shadow", "Turn The Keys", "Encrypted Hangman", "The Heart", "42", "501", "Access Codes", "SUSadmin", "Custom Keys", "Simon", "Damocles Lumber", "Module Maneuvers", "Mystery Widget", "X", "Y", "[BIG SHOT]", "Castor", "Pollux", "Turn The Key", "The Time Keeper", "Timing is Everything", "Bamboozling Time Keeper", "Password Destroyer", "OmegaDestroyer", "Zener Cards", "Doomsday Button", "Red Light Green Light", "Again", "Piano Paradox", "OMISSION", "Queen's War"};
}
